### ISSUE TITLE
"S" list didn't show up and it shows timeout error

### ISSUE THREAD

**Issue by DerekTso** [phobal/shadowsocks-free-account#12]
node version: v8.9.4

I use Chromium(68.0.3414.0) to open the url [https://free-ss.site](https://free-ss.site) and the S account list didn't show up. But it shows up on Chrome(63.0.3239.132).

And i guess the page.waitForNavigation() timeouts, then it shows error on node

> (node:11924) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: waiting failed: timeout 30000ms exceeded warning.js:18
> (node:11924) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Chromium**
![image](https://user-images.githubusercontent.com/10363328/40587707-78704c2e-6205-11e8-86c1-8d870ad6d5b7.png)

**Chrome**
![image](https://user-images.githubusercontent.com/10363328/40587750-f7d991a0-6205-11e8-9e4f-b9883f29bf89.png)

**Comment by monotonewang** [comment]
Can not get ss.json

**Comment by phobal** [comment]
源网站已关闭，所以使用不了了，建议花点小钱买个收费版的吧
