### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by dianxiaopao** [phobal/shadowsocks-free-account#13]
node v8.9.4
可以弹出页面，但是控制台报错

E:\2018\code\ShadowSocksSpider (master -> origin) (ssspider@0.1.0)
λ node app.js
(node:10672) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: Navigation Timeout Exceeded: 30000ms exceeded
(node:10672) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by phobal** [comment]
源网站已关闭，所以使用不了了，建议花点小钱买个收费版的吧
