### ISSUE TITLE
能不能给安卓的ss做一个

### ISSUE THREAD

**Issue by Maybe0019** [phobal/shadowsocks-free-account#2]
能不能给安卓的ssr做一个订阅？

**Comment by phobal** [comment]
@Maybe0019 现在身边没有 Android 手机，接下来我在做这块教程的时候研究一下 Android 版本的 SS

**Comment by Maybe0019** [comment]
安卓的ssr订阅好像就是一个txt文件的链接，txt格式就不知道了，应该大同小异吧

**Comment by Liqianyu** [comment]
https://shadowsocks.org/en/spec/SIP002-URI-Scheme.html
https://github.com/shadowsocksrr/shadowsocks-rss/wiki/Subscribe-%E6%9C%8D%E5%8A%A1%E5%99%A8%E8%AE%A2%E9%98%85%E6%8E%A5%E5%8F%A3%E6%96%87%E6%A1%A3

**Comment by phobal** [comment]
送你们一个订阅地址 https://www.diguass.me/subscribe/8400
