### ISSUE TITLE
node app.js 现在报错了。

### ISSUE THREAD

**Issue by hupan508** [phobal/shadowsocks-free-account#5]
![image](https://user-images.githubusercontent.com/5687025/33811838-994ea7d8-de52-11e7-9b4f-53aa2fa80659.png)
求处理。。。关注中

**Comment by phobal** [comment]
@hupan508 已解决，原因是源网站地址变了，我把 controller 里的地址替换掉以后，忘记把 app 里的给替换掉了，谢谢提醒
