### ISSUE TITLE
多谢修改，还是报错了。你这工具原先挺好用的

### ISSUE THREAD

**Issue by hupan508** [phobal/shadowsocks-free-account#6]
![image](https://user-images.githubusercontent.com/5687025/33818715-6fa9b48e-de81-11e7-9c33-7799dc0d2577.png)

**Comment by hupan508** [comment]
可以了。少了个ss.json的文件！

**Comment by phobal** [comment]
@hupan508 这里是有个 bug,已修复，感谢指出
