### ISSUE TITLE
新版本报错哦

### ISSUE THREAD

**Issue by weizhang93** [phobal/shadowsocks-free-account#7]
![vt9drfw e_x 1 d h x is2](https://user-images.githubusercontent.com/13012211/34327013-c5c40004-e8f4-11e7-881d-a6d032a695f8.png)

![pj e70e vkmt857uv qlt4](https://user-images.githubusercontent.com/13012211/34327022-f0a7adfc-e8f4-11e7-9f25-f475d2c8a4d7.png)

**Comment by hupan508** [comment]
我也同样报错。楼主维护一下啊

**Comment by phobal** [comment]
源网站的防爬策略变复杂了，正在寻找解决方案

**Comment by phobal** [comment]
@weizhang93 @hupan508 最近版本采用了 chrome 59 新出的 Handless 模式，配合官方的 [puppeteer](https://github.com/GoogleChrome/puppeteer)使用
