### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by luyiaya** [phobal/shadowsocks-free-account#8]
我安装了您说的node.js环境还是无法运行，提示语法错误，想不明白，(windows环境)您可以做一个集合了环境等所有需要因素的安装包吗，对于不会编程的我们来说有点不会解决了，简单操作还可以

**Comment by phobal** [comment]
提示什么语法错误呢，你可以贴出来我看下，原则上来讲，现在这个版本有用新语法 async 和 await，所以 node 版本最好安装 7.6 及其以上
