### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by ycqchang** [phobal/shadowsocks-free-account#9]
在win 上可以运行.如果能在linux上运行就好了.可惜在linux上运行会报Error: Failed to launch chrome! 如果不依赖chrome就很厉害啦.

**Comment by phobal** [comment]
可以设置的
`const browser = await puppeteer.launch({headless: false}); // default is true`
参考链接, 看一下 options 的配置
https://github.com/GoogleChrome/puppeteer/blob/master/docs/api.md#puppeteerlaunchoptions
